### PR TITLE
changed keyword restrict to __restrict__ to enable g++ agnosticism

### PR DESCRIPTION
**Pull request by Dan-McG**
Signed-off-by: Dan McGinn <Dan-McG@users.noreply.github.com>

### CODE REVIEW

**Comment by cleishm** [comment]
Hey @Dan-McG! Thanks. Do you have a link or something that describes the cases in which this is needed?

**Comment by cleishm** [comment]
Specifically - what are the rules about when `__restrict__` is defined, and when it isn't? Do we need an autoconf check to ensure `__restrict__` is always appropriately defined?

**Comment by Dan-McG** [comment]
Firstly thanks for creating this much needed driver! Solid work.  Here's a [link.](https://gcc.gnu.org/onlinedocs/gcc/Restricted-Pointers.html)  I think it's a pretty benign change.  As I understand it, `restrict` is a C99 qualifier keyword, and not part of any C++ standard, however the g++ compiler does support the feature but with the `__restrict__` keyword instead, which is also understood by gcc to be the C99 standard `restrict` keyword.  Annoyingly, `__restrict` is the appropriate keyword for VS C++ compiler I believe.  If you compile your example code with g++ instead of gcc you'll see the errors neo4j-client.h currently generates.

**Comment by cleishm** [comment]
Thanks @Dan-McG. Given the difference between GNU and VS C++, I'm guessing we need an autoconf check? Otherwise `__restrict__` will also give an error with VS?

**Comment by cleishm** [comment]
@Dan-McG: I take that back. Obviously an autoconf check will only work in the code of the project including the header. Which isn't so helpful.

So how about this? cb8b96a

**Comment by Dan-McG** [comment]
apologies, didn't have time to review cb8b96a998fc68872481ee4958e2360c1ee0924e before the 958ed13ed497dded33981b8a2fab25f9455caa7f commit to master.  this is not worth a pull request but  neo4j-client.h line44 needs `__restrict__` rather than `__restrict`.  I don't use Visual Studio so unable to check those additions.

**Comment by cleishm** [comment]
@Dan-McG I believe `__restrict` also works for the g++ compiler? Can you confirm in your case?

**Comment by Dan-McG** [comment]
ahh yep, all good

**Pull request closed without merging**
